### ISSUE TITLE
newlines on all std::cout statements in test-array

### ISSUE THREAD

**Issue by danielgaooooo** [rupark/CS4500A1P2#10]
if you do not append either std::endl or "\n" to your pass/fail print statements, it doesn't properly flush the stdout buffer and causes some print statements to skip, even if the test passes  
  
ex: https://github.com/rupark/CS4500A1P2/blob/master/test-array.cpp#L17 should have << std::endl at the end

**Comment by rupark** [comment]
Fixed in latest push. Thanks!
