### ISSUE TITLE
create some more methods

### ISSUE THREAD

**Issue by danielgaooooo** [rupark/CS4500A1P2#5]
add these methods:  
`Array(Array* other)` (constructor)  
`void append(Object* o)`  
`Object* remove(size_t index)`  
`bool contains(Object* o)`  
` size_t index_of(Object* o)`

**Comment by rupark** [comment]
Hi Daniel,
We will be merging our updated code which includes:
- push_back(Object* o) which sounds similar to the append method you asked for.

In terms of the other methods requested, we believe you will be able to implement them privately if necessary. 
- The remove function does not sound like an array functionality (more like a list). 
- The contains and index_of would be helpful private methods if you need them, but do not sound critical for the data structure. 
- Finally, the constructor which accepts an Array pointer sounds like a useful "private" constructor which you can implement if needed, and this is discussed in Piazza post @362. 

Please let us know if you have any questions or concerns with this! Thanks!
