### ISSUE TITLE
Can you guys add Bool, Integer, and Float wrapper classes?

### ISSUE THREAD

**Issue by EanMcDonaldWojciechowski** [rupark/CS4500A1P2#6]
Could you guys please add wrapper classes for the primitive types bool, int, and float? The spec says we need to be able to have those types in the array. They can be basic classes that inherit from Object so they can be stored in the array.

**Comment by rupark** [comment]
Hi,

We will be merging the changes you requested. This includes the int_w, float_w, and bool_w wrapper classes.

Please let us know if you have any other questions or concerns.

Thanks!
Mark and Kate
